exclude: grand_geckos/static
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
    - id: python-check-blanket-noqa
      name: Check for Blanket noqa
  - repo: https://github.com/PyCQA/isort
    rev: 5.9.2
    hooks:
    - id: isort
      name: Isort  - Auto-sort Imports
      exclude: tests
  - repo: https://github.com/ambv/black
    rev: 21.6b0
    hooks:
    - id: black
      name: Black  - Formatting
      exclude: tests
  - repo: https://github.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
    - id: flake8
      name: Flake8 - Code Quality
      exclude: tests
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
    - id: mypy
      name: Mypy   - Type Checker
      exclude: tests
